-- Risk Exposure Databricks Genie demo data setup.
-- GENERATED by scripts/gen-risk-demo-sql.py — do not edit by hand; edit the generator.
-- The catalog/schema already exist in the deployed workspace (Default Storage
-- metastore cannot CREATE CATALOG without a managed location), so we only USE them
-- and CREATE OR REPLACE the curated objects. scripts/run-demo-sql.sh rewrites
-- 'risk_demo' -> $DEMO_CATALOG and 'analytics' -> $DEMO_SCHEMA before running.

USE CATALOG risk_demo;
USE SCHEMA analytics;

CREATE OR REPLACE TABLE dim_broker (
  broker_id STRING COMMENT 'Unique broker identifier',
  broker_name STRING COMMENT 'Broker display name',
  broker_segment STRING COMMENT 'Commercial segment of the broker',
  broker_country STRING COMMENT 'Primary broker country'
)
USING DELTA
COMMENT 'Curated broker dimension for Risk Exposure Genie demo';

INSERT OVERWRITE dim_broker VALUES
  ('B001', 'North Trade Brokers', 'Enterprise', 'Netherlands'),
  ('B002', 'Iberia Credit Partners', 'SME', 'Spain'),
  ('B003', 'DACH Risk Advisors', 'Mid-Market', 'Germany'),
  ('B004', 'Benelux Coverage Group', 'Enterprise', 'Belgium'),
  ('B005', 'France Trade Assurance', 'SME', 'France'),
  ('B006', 'Nordic Credit Shield', 'Enterprise', 'Sweden'),
  ('B007', 'Italia Trade Risk', 'Mid-Market', 'Italy'),
  ('B008', 'UK Working Capital Partners', 'Enterprise', 'United Kingdom'),
  ('B009', 'Poland Receivables Hub', 'SME', 'Poland'),
  ('B010', 'Portugal Export Cover', 'SME', 'Portugal');

CREATE OR REPLACE TABLE fact_exposure (
  policy_id STRING COMMENT 'Policy identifier',
  broker_id STRING COMMENT 'Broker identifier linked to dim_broker',
  legal_entity STRING COMMENT 'Synthetic legal entity',
  country STRING COMMENT 'Exposure country',
  risk_class STRING COMMENT 'Risk class assigned by underwriting',
  product_line STRING COMMENT 'Insurance product line',
  fiscal_quarter STRING COMMENT 'Fiscal quarter in YYYY-Qn format',
  exposure_eur DECIMAL(18,2) COMMENT 'Total credit exposure in EUR',
  overdue_balance_eur DECIMAL(18,2) COMMENT 'Overdue outstanding balance in EUR'
)
USING DELTA
COMMENT 'Curated exposure fact table for Risk Exposure Genie demo';

INSERT OVERWRITE fact_exposure VALUES
  ('P10001', 'B001', 'Contoso NL', 'Netherlands', 'A', 'Trade Credit', '2025-Q1', 1197000.00, 13000.00),
  ('P10002', 'B001', 'Contoso NL', 'Netherlands', 'B', 'Surety', '2025-Q1', 1627000.00, 63000.00),
  ('P10003', 'B001', 'Contoso NL', 'Netherlands', 'B', 'Surety', '2025-Q2', 1558000.00, 61000.00),
  ('P10004', 'B001', 'Contoso NL', 'Netherlands', 'C', 'Collections', '2025-Q2', 2051000.00, 233000.00),
  ('P10005', 'B001', 'Contoso NL', 'Netherlands', 'C', 'Collections', '2025-Q3', 1976000.00, 225000.00),
  ('P10006', 'B001', 'Contoso NL', 'Netherlands', 'A', 'Bonding', '2025-Q3', 1910000.00, 34000.00),
  ('P10007', 'B001', 'Contoso NL', 'Netherlands', 'A', 'Bonding', '2025-Q4', 1813000.00, 33000.00),
  ('P10008', 'B001', 'Contoso NL', 'Netherlands', 'B', 'Trade Credit', '2025-Q4', 1539000.00, 95000.00),
  ('P10009', 'B001', 'Contoso NL', 'Netherlands', 'B', 'Trade Credit', '2026-Q1', 1471000.00, 90000.00),
  ('P10010', 'B001', 'Contoso NL', 'Netherlands', 'C', 'Surety', '2026-Q1', 1965000.00, 151000.00),
  ('P10011', 'B001', 'Contoso NL', 'Netherlands', 'C', 'Surety', '2026-Q2', 1890000.00, 146000.00),
  ('P10012', 'B001', 'Contoso NL', 'Netherlands', 'A', 'Collections', '2026-Q2', 1848000.00, 24000.00),
  ('P10013', 'B001', 'Contoso NL', 'Netherlands', 'A', 'Collections', '2026-Q3', 1752000.00, 23000.00),
  ('P10014', 'B001', 'Contoso NL', 'Netherlands', 'B', 'Bonding', '2026-Q3', 2320000.00, 108000.00),
  ('P10015', 'B001', 'Contoso NL', 'Netherlands', 'B', 'Bonding', '2026-Q4', 2215000.00, 103000.00),
  ('P10016', 'B001', 'Contoso NL', 'Netherlands', 'C', 'Trade Credit', '2026-Q4', 1847000.00, 244000.00),
  ('P10017', 'B002', 'Contoso ES', 'Spain', 'C', 'Surety', '2025-Q1', 672000.00, 64000.00),
  ('P10018', 'B002', 'Contoso ES', 'Spain', 'A', 'Collections', '2025-Q2', 629000.00, 10000.00),
  ('P10019', 'B002', 'Contoso ES', 'Spain', 'B', 'Bonding', '2025-Q3', 794000.00, 43000.00),
  ('P10020', 'B002', 'Contoso ES', 'Spain', 'C', 'Trade Credit', '2025-Q4', 635000.00, 95000.00),
  ('P10021', 'B002', 'Contoso ES', 'Spain', 'A', 'Surety', '2026-Q1', 602000.00, 6000.00),
  ('P10022', 'B002', 'Contoso ES', 'Spain', 'B', 'Collections', '2026-Q2', 768000.00, 30000.00),
  ('P10023', 'B002', 'Contoso ES', 'Spain', 'C', 'Bonding', '2026-Q3', 958000.00, 109000.00),
  ('P10024', 'B002', 'Contoso ES', 'Spain', 'A', 'Trade Credit', '2026-Q4', 566000.00, 10000.00),
  ('P10025', 'B003', 'Contoso DE', 'Germany', 'B', 'Collections', '2025-Q1', 1082000.00, 50000.00),
  ('P10026', 'B003', 'Contoso DE', 'Germany', 'C', 'Bonding', '2025-Q2', 1348000.00, 178000.00),
  ('P10027', 'B003', 'Contoso DE', 'Germany', 'A', 'Trade Credit', '2025-Q3', 805000.00, 17000.00),
  ('P10028', 'B003', 'Contoso DE', 'Germany', 'B', 'Surety', '2025-Q4', 1038000.00, 33000.00),
  ('P10029', 'B003', 'Contoso DE', 'Germany', 'C', 'Collections', '2026-Q1', 1307000.00, 125000.00),
  ('P10030', 'B003', 'Contoso DE', 'Germany', 'A', 'Bonding', '2026-Q2', 1215000.00, 19000.00),
  ('P10031', 'B003', 'Contoso DE', 'Germany', 'B', 'Trade Credit', '2026-Q3', 977000.00, 53000.00),
  ('P10032', 'B003', 'Contoso DE', 'Germany', 'C', 'Surety', '2026-Q4', 1246000.00, 187000.00),
  ('P10033', 'B004', 'Contoso BE', 'Belgium', 'A', 'Bonding', '2025-Q1', 1885000.00, 34000.00),
  ('P10034', 'B004', 'Contoso BE', 'Belgium', 'B', 'Trade Credit', '2025-Q1', 1572000.00, 97000.00),
  ('P10035', 'B004', 'Contoso BE', 'Belgium', 'B', 'Trade Credit', '2025-Q2', 1515000.00, 93000.00),
  ('P10036', 'B004', 'Contoso BE', 'Belgium', 'C', 'Surety', '2025-Q2', 1503000.00, 116000.00),
  ('P10037', 'B004', 'Contoso BE', 'Belgium', 'C', 'Surety', '2025-Q3', 1428000.00, 110000.00),
  ('P10038', 'B004', 'Contoso BE', 'Belgium', 'A', 'Collections', '2025-Q3', 1913000.00, 25000.00),
  ('P10039', 'B004', 'Contoso BE', 'Belgium', 'A', 'Collections', '2025-Q4', 1830000.00, 24000.00),
  ('P10040', 'B004', 'Contoso BE', 'Belgium', 'B', 'Bonding', '2025-Q4', 2382000.00, 111000.00),
  ('P10041', 'B004', 'Contoso BE', 'Belgium', 'B', 'Bonding', '2026-Q1', 2292000.00, 107000.00),
  ('P10042', 'B004', 'Contoso BE', 'Belgium', 'C', 'Trade Credit', '2026-Q1', 1420000.00, 187000.00),
  ('P10043', 'B004', 'Contoso BE', 'Belgium', 'C', 'Trade Credit', '2026-Q2', 1346000.00, 178000.00),
  ('P10044', 'B004', 'Contoso BE', 'Belgium', 'A', 'Surety', '2026-Q2', 1830000.00, 38000.00),
  ('P10045', 'B004', 'Contoso BE', 'Belgium', 'A', 'Surety', '2026-Q3', 1748000.00, 36000.00),
  ('P10046', 'B004', 'Contoso BE', 'Belgium', 'B', 'Collections', '2026-Q3', 2301000.00, 72000.00),
  ('P10047', 'B004', 'Contoso BE', 'Belgium', 'B', 'Collections', '2026-Q4', 2211000.00, 70000.00),
  ('P10048', 'B004', 'Contoso BE', 'Belgium', 'C', 'Bonding', '2026-Q4', 2137000.00, 204000.00),
  ('P10049', 'B005', 'Contoso FR', 'France', 'C', 'Trade Credit', '2025-Q1', 482000.00, 72000.00),
  ('P10050', 'B005', 'Contoso FR', 'France', 'A', 'Surety', '2025-Q2', 625000.00, 7000.00),
  ('P10051', 'B005', 'Contoso FR', 'France', 'B', 'Collections', '2025-Q3', 790000.00, 31000.00),
  ('P10052', 'B005', 'Contoso FR', 'France', 'C', 'Bonding', '2025-Q4', 730000.00, 83000.00),
  ('P10053', 'B005', 'Contoso FR', 'France', 'A', 'Trade Credit', '2026-Q1', 590000.00, 11000.00),
  ('P10054', 'B005', 'Contoso FR', 'France', 'B', 'Surety', '2026-Q2', 756000.00, 46000.00),
  ('P10055', 'B005', 'Contoso FR', 'France', 'C', 'Collections', '2026-Q3', 705000.00, 54000.00),
  ('P10056', 'B005', 'Contoso FR', 'France', 'A', 'Bonding', '2026-Q4', 888000.00, 12000.00),
  ('P10057', 'B006', 'Contoso SE', 'Sweden', 'B', 'Surety', '2025-Q1', 1787000.00, 56000.00),
  ('P10058', 'B006', 'Contoso SE', 'Sweden', 'C', 'Collections', '2025-Q1', 1762000.00, 168000.00),
  ('P10059', 'B006', 'Contoso SE', 'Sweden', 'C', 'Collections', '2025-Q2', 1684000.00, 161000.00),
  ('P10060', 'B006', 'Contoso SE', 'Sweden', 'A', 'Bonding', '2025-Q2', 2203000.00, 34000.00),
  ('P10061', 'B006', 'Contoso SE', 'Sweden', 'A', 'Bonding', '2025-Q3', 2118000.00, 33000.00),
  ('P10062', 'B006', 'Contoso SE', 'Sweden', 'B', 'Trade Credit', '2025-Q3', 1306000.00, 71000.00),
  ('P10063', 'B006', 'Contoso SE', 'Sweden', 'B', 'Trade Credit', '2025-Q4', 1690000.00, 91000.00),
  ('P10064', 'B006', 'Contoso SE', 'Sweden', 'C', 'Surety', '2025-Q4', 1691000.00, 254000.00),
  ('P10065', 'B006', 'Contoso SE', 'Sweden', 'C', 'Surety', '2026-Q1', 1613000.00, 242000.00),
  ('P10066', 'B006', 'Contoso SE', 'Sweden', 'A', 'Collections', '2026-Q1', 2135000.00, 22000.00),
  ('P10067', 'B006', 'Contoso SE', 'Sweden', 'A', 'Collections', '2026-Q2', 2050000.00, 22000.00),
  ('P10068', 'B006', 'Contoso SE', 'Sweden', 'B', 'Bonding', '2026-Q2', 1972000.00, 77000.00),
  ('P10069', 'B006', 'Contoso SE', 'Sweden', 'B', 'Bonding', '2026-Q3', 2548000.00, 99000.00),
  ('P10070', 'B006', 'Contoso SE', 'Sweden', 'C', 'Trade Credit', '2026-Q3', 1592000.00, 181000.00),
  ('P10071', 'B006', 'Contoso SE', 'Sweden', 'C', 'Trade Credit', '2026-Q4', 1517000.00, 172000.00),
  ('P10072', 'B006', 'Contoso SE', 'Sweden', 'A', 'Surety', '2026-Q4', 2037000.00, 37000.00),
  ('P10073', 'B007', 'Contoso IT', 'Italy', 'A', 'Collections', '2025-Q1', 1117000.00, 15000.00),
  ('P10074', 'B007', 'Contoso IT', 'Italy', 'B', 'Bonding', '2025-Q2', 1026000.00, 48000.00),
  ('P10075', 'B007', 'Contoso IT', 'Italy', 'C', 'Trade Credit', '2025-Q3', 834000.00, 110000.00),
  ('P10076', 'B007', 'Contoso IT', 'Italy', 'A', 'Surety', '2025-Q4', 1072000.00, 22000.00),
  ('P10077', 'B007', 'Contoso IT', 'Italy', 'B', 'Collections', '2026-Q1', 995000.00, 31000.00),
  ('P10078', 'B007', 'Contoso IT', 'Italy', 'C', 'Bonding', '2026-Q2', 1259000.00, 120000.00),
  ('P10079', 'B007', 'Contoso IT', 'Italy', 'A', 'Trade Credit', '2026-Q3', 1009000.00, 16000.00),
  ('P10080', 'B007', 'Contoso IT', 'Italy', 'B', 'Surety', '2026-Q4', 949000.00, 51000.00),
  ('P10081', 'B008', 'Contoso UK', 'United Kingdom', 'C', 'Bonding', '2025-Q1', 1951000.00, 222000.00),
  ('P10082', 'B008', 'Contoso UK', 'United Kingdom', 'A', 'Trade Credit', '2025-Q1', 1197000.00, 22000.00),
  ('P10083', 'B008', 'Contoso UK', 'United Kingdom', 'A', 'Trade Credit', '2025-Q2', 1563000.00, 28000.00),
  ('P10084', 'B008', 'Contoso UK', 'United Kingdom', 'B', 'Surety', '2025-Q2', 1558000.00, 96000.00),
  ('P10085', 'B008', 'Contoso UK', 'United Kingdom', 'B', 'Surety', '2025-Q3', 1484000.00, 91000.00),
  ('P10086', 'B008', 'Contoso UK', 'United Kingdom', 'C', 'Collections', '2025-Q3', 1976000.00, 152000.00),
  ('P10087', 'B008', 'Contoso UK', 'United Kingdom', 'C', 'Collections', '2025-Q4', 1894000.00, 146000.00),
  ('P10088', 'B008', 'Contoso UK', 'United Kingdom', 'A', 'Bonding', '2025-Q4', 1813000.00, 24000.00),
  ('P10089', 'B008', 'Contoso UK', 'United Kingdom', 'A', 'Bonding', '2026-Q1', 2364000.00, 31000.00),
  ('P10090', 'B008', 'Contoso UK', 'United Kingdom', 'B', 'Trade Credit', '2026-Q1', 1471000.00, 68000.00),
  ('P10091', 'B008', 'Contoso UK', 'United Kingdom', 'B', 'Trade Credit', '2026-Q2', 1399000.00, 65000.00),
  ('P10092', 'B008', 'Contoso UK', 'United Kingdom', 'C', 'Surety', '2026-Q2', 1890000.00, 249000.00),
  ('P10093', 'B008', 'Contoso UK', 'United Kingdom', 'C', 'Surety', '2026-Q3', 1809000.00, 239000.00),
  ('P10094', 'B008', 'Contoso UK', 'United Kingdom', 'A', 'Collections', '2026-Q3', 1752000.00, 36000.00),
  ('P10095', 'B008', 'Contoso UK', 'United Kingdom', 'A', 'Collections', '2026-Q4', 2281000.00, 47000.00),
  ('P10096', 'B008', 'Contoso UK', 'United Kingdom', 'B', 'Bonding', '2026-Q4', 2215000.00, 70000.00),
  ('P10097', 'B009', 'Contoso PL', 'Poland', 'B', 'Trade Credit', '2025-Q1', 500000.00, 27000.00),
  ('P10098', 'B009', 'Contoso PL', 'Poland', 'C', 'Surety', '2025-Q2', 646000.00, 97000.00),
  ('P10099', 'B009', 'Contoso PL', 'Poland', 'A', 'Collections', '2025-Q3', 814000.00, 9000.00),
  ('P10100', 'B009', 'Contoso PL', 'Poland', 'B', 'Bonding', '2025-Q4', 758000.00, 30000.00),
  ('P10101', 'B009', 'Contoso PL', 'Poland', 'C', 'Trade Credit', '2026-Q1', 610000.00, 69000.00),
  ('P10102', 'B009', 'Contoso PL', 'Poland', 'A', 'Surety', '2026-Q2', 779000.00, 14000.00),
  ('P10103', 'B009', 'Contoso PL', 'Poland', 'B', 'Collections', '2026-Q3', 732000.00, 45000.00),
  ('P10104', 'B009', 'Contoso PL', 'Poland', 'C', 'Bonding', '2026-Q4', 918000.00, 71000.00),
  ('P10105', 'B010', 'Contoso PT', 'Portugal', 'A', 'Surety', '2025-Q1', 527000.00, 11000.00),
  ('P10106', 'B010', 'Contoso PT', 'Portugal', 'B', 'Collections', '2025-Q2', 676000.00, 21000.00),
  ('P10107', 'B010', 'Contoso PT', 'Portugal', 'C', 'Bonding', '2025-Q3', 848000.00, 81000.00),
  ('P10108', 'B010', 'Contoso PT', 'Portugal', 'A', 'Trade Credit', '2025-Q4', 499000.00, 8000.00),
  ('P10109', 'B010', 'Contoso PT', 'Portugal', 'B', 'Surety', '2026-Q1', 648000.00, 35000.00),
  ('P10110', 'B010', 'Contoso PT', 'Portugal', 'C', 'Collections', '2026-Q2', 820000.00, 123000.00),
  ('P10111', 'B010', 'Contoso PT', 'Portugal', 'A', 'Bonding', '2026-Q3', 752000.00, 8000.00),
  ('P10112', 'B010', 'Contoso PT', 'Portugal', 'B', 'Trade Credit', '2026-Q4', 609000.00, 24000.00);

CREATE OR REPLACE TABLE fact_claim (
  claim_id STRING COMMENT 'Claim identifier',
  policy_id STRING COMMENT 'Policy identifier linked to fact_exposure',
  claim_status STRING COMMENT 'Lifecycle status of the claim',
  claim_amount_eur DECIMAL(18,2) COMMENT 'Claim amount in EUR',
  claim_month STRING COMMENT 'Claim month in YYYY-MM format'
)
USING DELTA
COMMENT 'Curated claims fact table for Risk Exposure Genie demo';

INSERT OVERWRITE fact_claim VALUES
  ('C9001', 'P10004', 'Open', 280000.00, '2025-04'),
  ('C9002', 'P10010', 'Open', 121000.00, '2026-01'),
  ('C9003', 'P10016', 'Open', 293000.00, '2026-10'),
  ('C9004', 'P10019', 'Open', 43000.00, '2025-07'),
  ('C9005', 'P10022', 'Open', 31000.00, '2026-04'),
  ('C9006', 'P10025', 'Open', 32000.00, '2025-01'),
  ('C9007', 'P10028', 'Open', 62000.00, '2025-10'),
  ('C9008', 'P10031', 'Open', 53000.00, '2026-07'),
  ('C9009', 'P10034', 'Open', 78000.00, '2025-01'),
  ('C9010', 'P10037', 'Open', 66000.00, '2025-07'),
  ('C9011', 'P10040', 'Open', 143000.00, '2025-10'),
  ('C9012', 'P10043', 'Open', 178000.00, '2026-04'),
  ('C9013', 'P10046', 'Open', 92000.00, '2026-07'),
  ('C9014', 'P10049', 'Open', 43000.00, '2025-01'),
  ('C9015', 'P10052', 'Open', 100000.00, '2025-10'),
  ('C9016', 'P10055', 'Open', 54000.00, '2026-07'),
  ('C9017', 'P10058', 'Open', 134000.00, '2025-01'),
  ('C9018', 'P10064', 'Open', 305000.00, '2025-10'),
  ('C9019', 'P10070', 'Open', 145000.00, '2026-07'),
  ('C9020', 'P10085', 'Open', 55000.00, '2025-07'),
  ('C9021', 'P10091', 'Open', 70000.00, '2026-04'),
  ('C9022', 'P10097', 'Open', 16000.00, '2025-01'),
  ('C9023', 'P10100', 'Open', 45000.00, '2025-10'),
  ('C9024', 'P10103', 'Open', 45000.00, '2026-07'),
  ('C9025', 'P10106', 'Open', 27000.00, '2025-04'),
  ('C9026', 'P10109', 'Open', 21000.00, '2026-01'),
  ('C9027', 'P10112', 'Open', 37000.00, '2026-10');

-- View name matches the deployed Genie Space object (vw_uc3_genie_exposure_claims).
-- Views are not materialized, so replacing the tables above already refreshes it,
-- but CREATE OR REPLACE keeps the contract explicit and the script idempotent.
CREATE OR REPLACE VIEW vw_uc3_genie_exposure_claims
COMMENT 'Genie-ready curated view joining exposure, broker and claim signals for business questions'
AS
SELECT
  e.fiscal_quarter,
  e.country,
  e.legal_entity,
  e.risk_class,
  e.product_line,
  b.broker_segment,
  b.broker_name,
  COUNT(DISTINCT e.policy_id) AS policy_count,
  SUM(e.exposure_eur) AS total_exposure_eur,
  SUM(e.overdue_balance_eur) AS total_overdue_balance_eur,
  SUM(COALESCE(c.claim_amount_eur, 0)) AS total_claim_amount_eur,
  COUNT(DISTINCT c.claim_id) AS claim_count
FROM fact_exposure e
JOIN dim_broker b ON e.broker_id = b.broker_id
LEFT JOIN fact_claim c ON e.policy_id = c.policy_id
GROUP BY ALL;

-- Useful checks for the demo:
SELECT * FROM vw_uc3_genie_exposure_claims ORDER BY fiscal_quarter, country;
